version: '3.7'
volumes:
  database_data:
    driver: local
services:
  db:
    container_name: postgres_rest_api_go
    image: 'postgres:latest' # use latest official postgres version
    ports:
      - "5436:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - database_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - '12080:8080'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    env_file:
      - database.env  # configure postgres
    links:
      - db

